name = "PseudostableRecurrences"
uuid = "4f7db8a5-8d22-4d9a-baad-9979a979c0ae"
authors = ["Tianyi Pu <912396513@qq.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
